### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Cloudperry** [kbjakex/tiralab-calculator#1]
I'm going to add a review here tomorrow.

**Comment by Cloudperry** [comment]
# About this peer review
The project was downloaded on 9.10. I'm using rust nightly 1.66 from rustup. A lot of the code I can't really review properly, because I have only programmed in Lua, Python, Nim, C#, Java and C. Right now I can only program Nim, Python and Lua and the rest of the languages I have forgotten (or not used enough to really know). So I will mostly focus on reviewing the actual program and the project structure.

# Brief code review
The program seems to be very logically split into different modules. However ast.rs is a pretty weird name for that module as it seems to be about defining the operators. Maybe it should be called operators.rs or something?

From the few struct definitions and very basic functions that I understood it seems that the naming is good and the data structures used make sense. Maybe the floats could have been replaced by some decimal type like the one in "rust_decimal" crate. Most calculators I have used don't use floats, because of the classic unrepresentable numbers like 0.1 + 0.2 != 0.3. I know that its not super important for this course and the algorithms, but it would make the user experience a lot better.

# Bugs and suggestions for improvement
I noticed this very small bug in the user interface when for example incrementing a variable by 1 (happens whenever you change a variable's value). It should say x changed from 3 to 4.
```
> x = 3
> x = x + 1
x changed from 4 to 4
```
For some reason function declarations seemed to just not work. For example defining the function f(x) = 2x gave this output.
```
> f(x) = 2x
'LeftParen' not allowed in function declaration!
```

Typing any string and a number in parentheses (like a function call) returns the number even when the string isn't a variable or a function.
```
> aaa (1)
1
> b(1)
1
```

I saw in the documentation that declaring the same function with different number of parameters (function overloading) is not supported. I don't think that is a problem at all. In math notation it seems very rare to have a function with the same name, but different arguments. You also mentioned a function with 0 arguments, but maybe that shouldn't even be allowed. Is it even a function if it has no parameters it depends on?

# Testing and documentation
The project has good and concise documentation. There are a lot of tests and test coverage seems good. From the tests that I read, most of them seemed to test the parsing and whether the parser accepts some syntax or not. Maybe some of the tests should be written to run a string through the entire program and check that it evaluates to the correct number value? I see that in state.rs you have some tests that enter expressions as multiple strings and check that it evaluates to the correct value. However those tests don't enter the expressions as a single string in the format a user would enter to the app.

**Comment by kbjakex** [comment]
Thanks for the feedback!

> However ast.rs is a pretty weird name for that module as it seems to be about defining the operators.

Indeed. I used to have an actual AST in here, which I removed yesterday, and forgot to reconsider the filename. Renamed.

> Maybe the floats could have been replaced by some decimal type like the one in "rust_decimal" crate

True! I want to see if I can squeeze in a three-type type system during the remaining weeks, with which I could support exact calculations using fractions where possible, and decimal as a fallback (and boolean as the third type, though not yet sure of that). I'll switch to using a decimal type in any case.

> because of the classic unrepresentable numbers like 0.1 + 0.2 != 0.3

Ha, indeed.

> I noticed this very small bug in the user interface when for example incrementing a variable by 1 (happens whenever you change a variable's value). It should say x changed from 3 to 4.
> Typing any string and a number in parentheses (like a function call) returns the number even when the string isn't a variable or a function.

Good catches, thanks, fixed.

> For some reason function declarations seemed to just not work.

That is certainly bizarre 🤔 It has been tested on 3 platforms (Mac, Windows & Linux) and tests (unit tests & manual testing) passed on all three, but no doubt it didn't work for you. Did test and the function does work on my end. Hmm. Not too sure how to begin debugging this one... 

That did reveal that I was printing debug names of the tokens instead of what they are (`LeftParen` instead of `(`) too, fixed that.

> I saw in the documentation that declaring the same function with different number of parameters (function overloading) is not supported. I don't think that is a problem at all. In math notation it seems very rare to have a function with the same name, but different arguments. You also mentioned a function with 0 arguments, but maybe that shouldn't even be allowed. Is it even a function if it has no parameters it depends on?

I think I'll indeed follow math conventions here and disallow overloading. I considered not allowing zero-argument functions, but it does actually have a use, because you can update the functions it calls, so it's effectively an always-up-to-date constant:
```console
> g(x) = 2x / 3
> h(x) = (x+2)/3
> f() = g(h(5))
> f()
2.6666666666666665
> g(x) = 2x / 5
> f()
1.6
```
Niche, but since it works, I think I'll leave it in for now. It does have a slight inconsistency in that any variables that are referenced won't refer to the updated values so the argument to keep is half moot already...


> Maybe some of the tests should be written to run a string through the entire program and check that it evaluates to the correct number value? I see that in state.rs you have some tests that enter expressions as multiple strings and check that it evaluates to the correct value. However those tests don't enter the expressions as a single string in the format a user would enter to the app.

I have this type of testing now in `main.rs` :)
